name: Developer tests

on: push

jobs:
  launch-tests:
    runs-on: ubuntu-latest
    container: openjdk:8-jdk-alpine

    steps:
      - uses: actions/checkout@v2
      - name: Launch tests with Maven
        run:  ./mvnw test
